### ISSUE TITLE
How to increase the default page size

### ISSUE THREAD

**Issue by pamarti** [oria/gridx#131]
Hi I'm having a working grid but I want to show 100 records instead of 10. I also got rid of PaginationBarDD to step 10/25/50/All. I also have Pagination enabled but it is displaying the pages based on 10 but not 100. How can I change this setting

```
            var grid = new Grid({
                store : itemGridStore,
                cacheClass : Async, 
                pageSize : 100,
                structure : columns,
                sortInitialOrder : {
                    colId : '1',
                    ascending : true
                },          
                barBottom : [ "gridx/support/Summary",
                        "gridx/support/DropDownPager"

                ],
                modules : [ SingleSort, Pagination, Bar, 
                        HiddenColumns, HeaderMenu ]
            }, 'gridNode');
```

Help is much appreciated. All you hard work is really great. Thanks!!
Sri

![screenshot063](https://f.cloud.github.com/assets/5643996/1295018/a0ccfe4a-309d-11e3-8fff-fab86f8b5191.jpg)

**Comment by vuppalaravikanth** [comment]
How to modify the default pagesizes
pageSizes : [5,10,25,50,100,0]

I tried the above code. But it is not updating the page sizes

**Comment by vuppalaravikanth** [comment]
The below code worked for pagination Bar sizes
paginationBarSizes : [5,10,50,100,0]
