### ISSUE TITLE
how to use JsonRest as server side store with gridx?

### ISSUE THREAD

**Issue by HaoKang** [oria/gridx#22]
when I use JsonRest  as a  store,the grid cant show the data. 
code like this:

```
require([
    'dojo/store/JsonRest',
    'gridx/Grid',
    'gridx/core/model/cache/Async',
    'gridx/modules/SingleSort',
    'gridx/modules/ColumnResizer',
        'dojo/data/ObjectStore',
    'gridx/modules/pagination/Pagination',
    'gridx/modules/pagination/PaginationBar',
    'dojo/domReady!'
],function(Store,Grid,Cache,Sort,ColumnResizer,ObjectStore,Pagination,PaginationBar){
    var jsonStore = new Store({target:"${ctx}/demo/user/listJson"});
    // var store = new ObjectStore({objectStore:jsonStore});
    var columns = [
        {field: 'id', name: 'ID'},
        {field: 'loginName', name: 'LONIN_NAME'},
        {field: 'name', name: 'NAME'},
        {field: 'registerDate', name: 'REGISTER_DATE'}
    ];

    var grid = new Grid({
        cacheClass: Cache,
        store: jsonStore,
        structure: columns,
        modules:[
             Sort,
             ColumnResizer
             Pagination,
             PaginationBar
        ],
         autoHeight: true
    }); 
    grid.placeAt("gridNode");
    grid.startup();

});
```

I find that , when I user ObjectStore to wrap the JsonRest ,the grid can show the data now,but sort is not work ,and the request url is like this "/demo/user/listJsonundefined?sort(+name)".
what's the problem?

**Comment by fbarroso24** [comment]
Has anyone run into issues with the back button on gridx?    

Here's the scenario:
pageSize is 100 (i.e. it requests 100 objects at a time)
gridX displays 10 object per page
cache is Async

Once I move to page 11, it requests items 100-199 as expected.  However, if I click on the back button it actually displays items 190-199 instead of 90-99?

Any ideas what's going on? Thanks in advance!

**Comment by VarunVerma3** [comment]
@ghost @fbarroso24 
I have same issue as I get all the data as once not according to Content-Range so can you help me?
