### ISSUE TITLE
Incorrect order when sorting dates

### ISSUE THREAD

**Issue by edabe** [oria/gridx#23]
The sorting feature is broken for dates. Apparently it will sort dates as literal strings rather than Date objects, resulting in errors such as:

```
1904/4/4 -> 1904/12/18 -> 1904/10/25
```

The sorting convention for dates is as follows (as defined by Excel):
- Sort in ascending order means from oldest to newest
  `4/5/2008 -> 10/26/2009 -> 11/3/2009`
- Sort in descending order means from newest to oldest
  `11/3/2009 -> 10/26/2009 -> 4/5/2008`

In order to reproduce this issue:
1. Open the "test_grid_singleSort.html" test (in gridx/tests/test_grid_singleSort.html)
2. Click on the header to sort column "Download Date" in ascending order
- The dates will be sorted in ascending order as expected, but looking closely one can see that the order is not always correct. 

In this example, it will sort these dates in the following sequence:

```
1904/10/25 -> 1904/12/18 -> 1904/4/4
```

The correct ascending order should be:

```
1904/4/4 -> 1904/10/25 -> 1904/12/18
```

Apparently the sorting is converting the dates into String and then sorting alphabetically, which works only some of the times.

**Comment by shwetap07** [comment]
I'm not getting proper sorted data for float data type.How do i sort them properly.
