### ISSUE TITLE
Advice for select-all with large virtual scrolling grids

### ISSUE THREAD

**Issue by dalelane** [oria/gridx#27]
I have a virtual scrolling grid, backed by a JsonRest store, using RowHeader, extendedSelect/Row and IndirectSelect. 

If there are a large number of rows (I have 100,000+) it leads to usability issues with the select-all checkbox in the column header. 

Under the covers, it's submitting a single REST request to fetch all 100,000+ items. If you wait long enough, it does work - all items are eventually selected. 

But because the request takes a while, the browser thinks the script has hung. Firefox, for example, opens an "Unresponsive script" error dialog offering to let the user kill the script. 

Is there any advice for this scenario, please?

I can see that the simplest advice would be for you to say that select-all is unadvisable for grids with large number of rows, but I'm hoping there will be something we can do. 

Ideally, it would be good if some "loading/waiting" indicator was displayed while the request was sent, perhaps with the request split into multiple separate REST requests so as to keep the script active and prevent the browser wanting to kill it? 

Or would it be possible for the request for select-all to somehow request IDs only rather than the whole items to reduce the overhead of the request?

**Comment by chenzhh** [comment]
We create a new branch for this request:
https://github.com/oria/gridx/tree/serverside_select_all

But might not compatible with other modules, user need to maintain the rest code if apply this way of selecting all rows.
