### ISSUE TITLE
Multi subrow support

### ISSUE THREAD

**Issue by allencblee** [oria/gridx#321]
Any plan to support the multi subrow feature like the one in dojox.DataGrid?

**Comment by hjzheng** [comment]
You mean that the multi subrow feature is tree grid feature? can you give some example ?

**Comment by allencblee** [comment]
I meant the row span and  col span support in dojox.DataGrid

**Comment by hjzheng** [comment]
@yurychika this is new requirement, are you plan to support it.

**Comment by yurychika** [comment]
Row & column span is not possible to implement so far according to the core of gridx. Currently, we can't and has no plan to implement this.
