### ISSUE TITLE
onSelected row

### ISSUE THREAD

**Issue by majordo** [oria/gridx#323]
Hello,
I'm using v. 1.3.7.
I've got a grid correctly working with "gridx/modules/select/Row" enabled.
The following piece of code monitor onSelected event:
```javascript
this.grid.connect(this.grid.select.row, 'onSelected', function(row){
       console.info("1>>",row,row.rawData())
});
```
Anyway, If I try to use "gridx/modules/extendedSelect/Row" to enable the select all button, the event connector doesn't work anymore.

Any suggestions?
How can I use event onSelected row with the module "gridx/modules/extendedSelect/Row" enabled?

Thanks in advance.

**Comment by hjzheng** [comment]
"gridx/modules/extendedSelect/Row" module not have "onSelected" event, you can try to use event: onSelectionChange(newSelectedIds, oldSelectedIds)
![qq 20150127162120](https://cloud.githubusercontent.com/assets/4166657/5915444/dd6c1b1e-a640-11e4-8cdf-6705a3a5f52f.png)

**Comment by majordo** [comment]
It works!
Thank you
Luca
