### ISSUE TITLE
Select (Highlight) a specific column

### ISSUE THREAD

**Issue by soufi** [oria/gridx#354]
Hi,

I am trying to add column selection by using the **onHeaderCellClick** listener. 

Now that I have my **column**, I would like to know if there is any way to highlight it, I couldn't find the **select** function in **cell** object neither **column** object ?

**Comment by sousarka** [comment]
You can use the gridx/modules/select/Column  (or gridx/modules/extendedSelect/Column, if needed) module which will provide you the following methods for column selections

Column.select = function(){
		// summary:
		//		Select this column.
	};
	Column.deselect = function(){
		// summary:
		//		Deselect this column.
	};
	Column.isSelected = function(){
		// summary:
		//		Whether this column is selected.
	};
