### ISSUE TITLE
Grid fails to create newline break on keypress ENTER for textarea editor in always editing mode

### ISSUE THREAD

**Issue by claracruz** [oria/gridx#362]
In alwaysEditing mode and when using a textarea, grid fails to create newline break on keypress ENTER.

Upon investigation, in modules/Edit.js, the following code in method "_onKey" is the root cause of the issue;

```
if (col.editable) {
    ....
}
```

Replacing that line with the following code fixes the issue;

   if(!col.alwaysEditing && col.editable){
          .....
    }

**Comment by jsonn** [comment]
Are you setting editorIgnoresEnter for your column?
